server:
  port: 5000

spring:
  application:
    name: filesharing-filehandler
  data:
    mongodb:
      uri: mongodb://admin:admin123456@localhost:27017/metadata?authSource=admin&authMechanism=SCRAM-SHA-256
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: tpnam1w3@gmail.com
    password: dxcd sxwu viga ozss
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: 1
      retries: 5
      batch-size: 32768
      linger-ms: 30
      buffer-memory: 67108864
      compression-type: lz4
      properties:
        max.block.ms: 10000
        request.timeout.ms: 20000
        delivery.timeout.ms: 30000
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
      auto-offset-reset: latest
      group-id: file-handler
    listener:
      ack-mode: manual
      concurrency: 1

kafka:
  topics:
    notification_email_sender: notification_email_sender
    video_encode_topic: video_encode_topic
    video_encode_result_topic: video_encode_result_topic
  authen: ${KAFKA_AUTH:false}
  username: ${KAFKA_USER:admin}
  password: ${KAFKA_PASS:adminKafka123}

minio:
  endpoint: http://localhost:9000
  access-key: 20YG284ICBVC7BL4I4LA
  secret-key: ySHIgqYkj1kvGexCa3kHsUAF+9FKUoQpM+vFZhzJ
  bucket-name: file-sharing
#  access-key: 5UVTKA00N1U9060FMZW0
#  secret-key: ZXd4xWM3hmiTZbgGVZ+LUJG2suVh0Vr3QiPjZjn0

application:
  security:
    jwt:
      expiration: 86400000 # 24 hours
      secret-key: nprtI/yUVAZiaZBTM7K1CYqEkrvXOPyeOIFq/1wCfzE=
      refresh-token:
        expiration: 604800000     # 7 days

springdoc:
  api-docs:
    enabled: true
    output-file: docs/filehandler-openapi.jsons
    path: /v3/api-docs
    resolve-schema-properties: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    filter: true
  paths-to-exclude: /api/auth/**
  packages-to-scan: org.example.filesharing.controllers
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  show-actuator: false
  writer-with-default-pretty-printer: true
  # Cấu hình để giữ nguyên tên method làm operationId
  override-with-generic-response: false
  use-management-port: false
  # Sử dụng tên method làm operationId
  operationsSorter: method
