<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.5.6</version>
		<relativePath/>
	</parent>

	<groupId>com.file.service</groupId>
	<artifactId>filesharing</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>pom</packaging>
	<name>filesharing</name>
	<description>Parent POM for FileSharing services</description>

	<properties>
		<java.version>21</java.version>
		<minio.version>8.5.7</minio.version>
		<openapi.version>2.7.0</openapi.version>
		<jwt.version>0.12.6</jwt.version>
		<apachecommon.version>1.4.0</apachecommon.version>
	</properties>

	<modules>
		<module>filesharing-filehandler</module>
		<module>filesharing-notification</module>
		<module>filesharing-videocodec</module>
		<module>filesharing-imagecodec</module>
	</modules>

	<dependencyManagement>
		<dependencies>
			<!-- Internal modules -->
			<dependency>
				<groupId>com.file.service</groupId>
				<artifactId>filesharing-filehandler</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.file.service</groupId>
				<artifactId>filesharing-notification</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.file.service</groupId>
				<artifactId>filesharing-videocodec</artifactId>
				<version>${project.version}</version>
			</dependency>


			<!-- External modules -->
			<dependency>
				<groupId>io.minio</groupId>
				<artifactId>minio</artifactId>
				<version>${minio.version}</version>
			</dependency>
			<dependency>
				<groupId>org.springdoc</groupId>
				<artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
				<version>${openapi.version}</version>
			</dependency>
			<dependency>
				<groupId>io.jsonwebtoken</groupId>
				<artifactId>jjwt-api</artifactId>
				<version>${jwt.version}</version>
			</dependency>
			<dependency>
				<groupId>io.jsonwebtoken</groupId>
				<artifactId>jjwt-impl</artifactId>
				<version>${jwt.version}</version>
				<scope>runtime</scope>
			</dependency>
			<dependency>
				<groupId>io.jsonwebtoken</groupId>
				<artifactId>jjwt-jackson</artifactId>
				<version>${jwt.version}</version>
				<scope>runtime</scope>
			</dependency>
			<dependency>
				<groupId>org.apache.commons</groupId>
				<artifactId>commons-exec</artifactId>
				<version>${apachecommon.version}</version>
			</dependency>
		</dependencies>
	</dependencyManagement>
</project>
