server:
  port: 5001

spring:
  application:
    name: filesharing-notification
  mail:
    host: smtp.gmail.com
    port: 587
    username: tpnam1w3@gmail.com
    password: dxcd sxwu viga ozss
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
  kafka:
    bootstrap-servers: localhost:9092